# The key and element characters #, !, =, and : are written with a preceding backslash to ensure that they are properly loaded.

       iipservDir = /operational_shared/mirador/img
       cantaloupeDir = /operational_shared/mirador/img
       manifestDir = /operational_shared/mirador/mirador_cantaloupe/
       altoOCR = /nas/vol03/lbs/alma/ocr-google/IMPORT-DONE-
#       altoxml = C:\\webapps\\IIIFAltoConvertor\\ALTO_XML\\project_google\\
       altojson = /nas/vol03/mirador/mirador/annotation/jsonGoogle/
       manifestUrl = /manifest/
       annotationServerUrl= https://services.libis.be/sas/search-api/
    importNumber = GoogleBooks_Scanning
//importNumber = KADOC_IIIF_EPeriodieken
startdatum = 2025/06/01
einddatum = 2025/06/02

#produktie   
//       iipserv = http://services.libis.be/iipsrv
        cantaloupe = http://services4.libis.be/iiif/2
        resolver = https://lib.is
#       url = jdbc:oracle:thin:@libis-db-rosetta.cc.kuleuven.be:1551/ROSETTAP.kuleuven.be
       url = jdbc:oracle:thin:@localhost:1551/ROSETTAP.kuleuven.be
		    connUsr = V2KU_rep00
		    connPwd = V2KU_rep00
		    conn_shrUsr = V2KU_SHR00
		    conn_shrPwd = V2KU_SHR00
		    conn_perUsr = V2KU_PER00
		    conn_perPwd = V2KU_PER00


#test
#	iipservDir = O\:/mirador/img
#        manifestDir = O\:/mirador/delivery/
#        m2 = http://libis-p-rosetta-3w.cc.kuleuven.be:80/m2
 #       iipserv = http://libis-p-rosetta-3w.cc.kuleuven.be:80/iipsrv
#	
 #       url = jdbc:oracle:thin:@libis-db-rosettaq.cc.kuleuven.be:1751/ROSETTAQ.kuleuven.be
#		    connUsr = V232_REP00
#		    connPwd = V232_REP00
#		    conn_shrUsr = V232_SHR00
#		    conn_shrPwd = V232_SHR00
#		    conn_perUsr = V232_PER00
#		    conn_perPwd = V232_PER00



	PDS_URL = http\://dps.exlibris.com/pds
        PDS_URL = https\://leuven-primo.hosted.exlibrisgroup.com/pds
	IE_WSDL_URL = http\://depot.lias.be/dpsws/repository/IEWebServices?wsdl
	

